### ISSUE TITLE
ctypes error: Wrong type

### ISSUE THREAD

**Issue by CookieComputing** [CookieComputing/mingus3#10]
```
Error
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/usr/local/lib/python3.6/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.6/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.6/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.6/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kevin/PycharmProjects/mingus3/unittest/test_fluidsynth.py", line 6, in <module>
    from mingus.midi import fluidsynth
  File "/home/kevin/PycharmProjects/mingus3/mingus/midi/fluidsynth.py", line 103, in <module>
    midi = FluidSynthSequencer()
  File "/home/kevin/PycharmProjects/mingus3/mingus/midi/fluidsynth.py", line 48, in __init__
    self.fs = fluidsynth.Synth()
  File "/home/kevin/PycharmProjects/mingus3/mingus/midi/pyfluidsynth.py", line 174, in __init__
    fluid_settings_setnum(st,  gain, 'synth.gain')
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

**Comment by CookieComputing** [comment]
It looks like CTypes expects a byte string, not a unicode string. I'll tag the post I found after I've confirmed the issue is resolved.

**Comment by CookieComputing** [comment]
For future references, the error was indeed a result of the [strings being unicode string](https://github.com/nwhitehead/pyfluidsynth/issues/2). I have updated the code and now it runs as expected.
