### ISSUE TITLE
Is removing redundant accidentals intended for non-notes?

### ISSUE THREAD

**Issue by CookieComputing** [CookieComputing/mingus3#5]
Consider the following code:
```
>>> notes.remove_redundant_accidentals("D###bb")
'D#'
```

This obviously works as intended, and can be seen as valid here:
```
>>> notes.is_valid_note("D###")
True
```

But also consider the following:
```
>>> notes.remove_redundant_accidentals("d###bbb")
'd'
```
This is unexpected: `d###bbb` is not a valid note.
```
>>> notes.is_valid_note("d###bbbb")
False
```
Is this an intended design?

**Comment by CookieComputing** [comment]
This could be a design choice that the original mingus developers had in mind, but I'm not entirely sure: I'll have to investigate further.

**Comment by CookieComputing** [comment]
Following an investigation, it seems that `note_to_int` does not intentionally allow this:
```
>>> notes.note_to_int("d###bbbb")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mingus/core/notes.py", line 111, in note_to_int
    raise NoteFormatError("Unknown note format '%s'" % note)
mingus.core.mt_exceptions.NoteFormatError: Unknown note format 'd###bbbb'
```
So this seems to be an oversight primarily.

**Comment by CookieComputing** [comment]
A contradiction to this behavior is also found in `augment()` and `diminish()`, whereby they accept invalid notes as well:

```
>>> notes.augment("3bbbb###")
'3bbbb####'
>>> notes.diminish("3bbbb###")
'3bbbb##'
>>> notes.diminish("dbbbb###")
'dbbbb##'
```

What should be the case for this design? I would argue that these methods should only process notes based on whether they were correct notes in the first place and keep this consistent throughout the code base. This can help in situations where users may inadvertently introduce malformed note strings, and could help them in those scenarios.

**Comment by CookieComputing** [comment]
Things get even more confusing when we look at `get_notes()` or even any of the intervals:

```
>>> keys.get_notes("c")
['C', 'D', 'Eb', 'F', 'G', 'Ab', 'Bb']
```

```
>>> intervals.second("C","c")
'D'
>>> intervals.second("c","C")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kevin/PycharmProjects/mingus3/mingus/core/intervals.py", line 83, in second
    return interval(key, note, 1)
  File "/home/kevin/PycharmProjects/mingus3/mingus/core/intervals.py", line 49, in interval
    raise KeyError("The start note '%s' is not a valid note" % start_note)
KeyError: "The start note 'c' is not a valid note"
```
We need to make the behavior uniform so that these subtle errors are cleaned up.

**Comment by CookieComputing** [comment]
I've reinforced note checking behavior for all methods in `notes.py`, so as a result, only valid notes can have anything be reduced. See #17  for changes.
