### ISSUE TITLE
int_to_note() provides range error for float values

### ISSUE THREAD

**Issue by CookieComputing** [CookieComputing/mingus3#9]
```
>>> notes.int_to_note(3.2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mingus/core/notes.py", line 68, in int_to_note
    raise RangeError('int out of bounds (0-11): %d ' % note_int)
mingus.core.mt_exceptions.RangeError: int out of bounds (0-11): 3 
>>> 
```

We probably want this to be a type error instead.

**Comment by CookieComputing** [comment]
This is more of a semantics problem with the code, as the code is still checked appropriately. Perhaps a better solution would be to just change the error message.
